name: CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: Run lint and tests
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: fake-key
      DEBUG: True
      SOCIAL_AUTH_FACEBOOK_KEY: fake
      SOCIAL_AUTH_FACEBOOK_SECRET: fake
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: fake
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: fake
      SOCIAL_AUTH_GITHUB_KEY: fake
      SOCIAL_AUTH_GITHUB_SECRET: fake
      VDOCHIPER_BASE_URL: fake
      VDOCHIPER_API_KEY: fake
      WKHTMLTOPDF_CMD: fake

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.5

    - name: Install Dependencies
      run: make ci-dependencies

    - name: Run Lint
      run: make lint

    - name: Run Test
      run: make test